Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit 4369de7af46605522bf7dbe3bc31d00b0eb4bee6.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".

NOKEYCHECK=True
GitOrigin-RevId: 8e728adcfedd97fbc3759b5533d0cbada6b68aa6