[compiler-rt] Allow to build on CYGWIN (#66348)
If you try to build `compiler-rt` on CYGWIN, you will get message:
```
error: Unsupported target
```
Adding support for this platform. just needs to add testing if
`__CYGWIN__` is defined into `lib\builtins\int_lib.h`.
NOKEYCHECK=True
GitOrigin-RevId: d0761d560a24b1b2b21f2cea67d19f3c244555ae