[builtins] Fix assembly in arm sync-ops.h
This assembly is part of a macro that was reformatted in D60351.
The missing space between push and { results in:

    Error: bad instruction `push{r4, r5,r6,lr}'

llvm-svn: 365957
NOKEYCHECK=True
GitOrigin-RevId: a205ebb09cc50e29e8d7edae6910de25baf69509