[compiler-rt] Fix a warning
This patch fixes:

  compiler-rt/lib/builtins/cpu_model.c:590:5: error: unannotated
  fall-through between switch labels [-Werror,-Wimplicit-fallthrough]

by adding a missing "break;".

NOKEYCHECK=True
GitOrigin-RevId: 4d8ea66d74cd355c267b27ca2dd04c821ae2331f