[hwasan] Exclude bcmp interceptor test from Android
This fixes a buildbot breakage (e.g.,
https://lab.llvm.org/buildbot/#/builders/77/builds/31422/steps/21/logs/stdio)
that was caused by the introduction of this test
(https://github.com/llvm/llvm-project/commit/ff1329e29709477472a93e9ce975f166f75999a3).

Build error from buildbot:
/var/lib/buildbot/sanitizer-buildbot6/sanitizer-x86_64-linux-android/build/llvm-project/compiler-rt/test/hwasan/TestCases/bcmp.cpp:18:10: error: use of undeclared identifier 'bcmp'
   18 |   return bcmp(p, a, size);

NOKEYCHECK=True
GitOrigin-RevId: 7b1e6851b65a4776e52602c2987b9861fbdc1170