[compiler-rt] Fix test broken by r354851.
error: CHECK: expected string not found in input
// CHECK: Uninitialized bytes in __interceptor_memcmp at offset 3

llvm-svn: 354852
NOKEYCHECK=True
GitOrigin-RevId: cb6b499fe6a783c1eab702791a2585063fe8d453