Revert 1689ad27af5 "[builtins] Implement rounding mode support for i386/x86_64"
It broke the build with MSVC:

fp_mode.c(20): error C2065: '__asm__': undeclared identifier

> Differential Revision: https://reviews.llvm.org/D69870

NOKEYCHECK=True
GitOrigin-RevId: a19f0eec94e195cac676d0d473882b48f4fded90