[TSan] guard lock_during_write flag on Apple platforms changes to exclude Go (#163204)
There are currently build errors when checking the TSan Go runtime due
to the implementation of this flag (as pointed out
[here](https://github.com/llvm/llvm-project/pull/157928#issuecomment-3397443983)):

```
 ../rtl/tsan_rtl.cpp:46:11: error: no member named 'cur_thread_init' in namespace '__tsan'
    46 |   __tsan::cur_thread_init()->in_internal_write_call = value;
       |           ^~~~~~~~~~~~~~~
 ../../sanitizer_common/sanitizer_mac.cpp:109:38: error: redefinition of '__tsan_set_in_internal_write_call'
   109 | SANITIZER_WEAK_ATTRIBUTE extern void __tsan_set_in_internal_write_call(
       |                                      ^
 ../rtl/tsan_rtl.cpp:45:13: note: previous definition is here
    45 | extern void __tsan_set_in_internal_write_call(bool value) {
       |             ^
```

This patch guards all changes related to the flag behind `!SANITIZER_GO`
to avoid these errors occurring.

NOKEYCHECK=True
GitOrigin-RevId: a263c34617a5aa735bfa4cd791edc252603cdf6d