[sanitizers] trace-pc-guard doesn't work on mac as well
fatal error: error in backend: Global variable '__sancov_gen_' has an
invalid section specifier '__sancov_guards': mach-o section specifier
requires a segment and section separated by a comma.

llvm-svn: 289507
NOKEYCHECK=True
GitOrigin-RevId: e20a4c8859edecdced8957d24bb57e838c3055fe